#!/bin/sh

PWD=`pwd`
cd /opt/sdk-xgs-robo/

if [ ! -z "`pidof bcm.user`" ]; then
	echo "Broadcom SDK has been run"
	exit
fi

insmod linux-kernel-bde.ko
insmod linux-user-bde.ko
A=`cat /proc/devices | grep -w linux-kernel-bde | cut -f1 -d" "`
B=`cat /proc/devices | grep -w linux-user-bde | cut -f1 -d" "`
mknod /dev/linux-kernel-bde c ${A} 0
mknod /dev/linux-user-bde c ${B} 0

./init.sh > /dev/null 2>&1 &

while [ ! -c /dev/linux-kernel-bde ] ||\
	[ ! -c /dev/linux-user-bde ]; do
	sleep 1
done
./bcm.user

rm -f /tmp/.BcmSdkShellIn
rm -f /tmp/.BcmSdkShellOut
rm -f /tmp/.BcmSdkReady

stty sane
cd $PWD
