#!/bin/bash
FP_INSTALL_DIR=/mnt/fastpath
FP_MOUNT_DIR=/mnt/application
RELOAD_FILE=/tmp/fp_reload_opt
DP_READY=/tmp/.SwitchDPReady
RELOAD_SYSTEM=0
RELOAD_FASTPATH=1
RELOAD_NONE=2
MODE_40G=`cat $FP_INSTALL_DIR/qsfp_mode_40g`

check_image() {
    if [ ! -s $FP_MOUNT_DIR/image2 ]; then
        cp $FP_MOUNT_DIR/image1 $FP_MOUNT_DIR/image2
    fi

    if [ ! -s $FP_INSTALL_DIR/image2 ]; then
        cp $FP_MOUNT_DIR/image2 $FP_INSTALL_DIR/image2
    fi
}

check_conf() {

rm $FP_MOUNT_DIR/rc.soc

    if [ "x$MODE_40G" == "x0" ]; then
        ln -s $FP_MOUNT_DIR/rc.soc.10g $FP_MOUNT_DIR/rc.soc
    else
        ln -s $FP_MOUNT_DIR/rc.soc.40g $FP_MOUNT_DIR/rc.soc
    fi

    if [ ! -s $FP_INSTALL_DIR/factory-defaults ]; then
        echo -n "copy factory-defaults to $FP_INSTALL_DIR/factory-defaults..."
        cp $FP_MOUNT_DIR/factory-defaults $FP_INSTALL_DIR/factory-defaults
        echo "done."
    fi

    if [ ! -s $FP_INSTALL_DIR/startup-config ]; then
        echo -n "apply factory-defaults to $FP_INSTALL_DIR/startup-config..."
        cp $FP_INSTALL_DIR/factory-defaults $FP_INSTALL_DIR/startup-config
        echo "done."
    fi
}

get_reload_opt() {
    if [ -f $RELOAD_FILE ]; then
        case "`cat $RELOAD_FILE`" in
            $RELOAD_FASTPATH*)
                return $RELOAD_FASTPATH
                ;;

            $RELOAD_NONE*)
                return $RELOAD_NONE
                ;;

            *)
                return $RELOAD_SYSTEM
                ;;
        esac
    else
        return $RELOAD_SYSTEM
    fi
}

   if [ -f $DP_READY ]; then
         echo "DataPlane Switch is Running..."
         exit 0
   fi

   check_image
   check_conf
   while [ 1 ]; do
       $FP_MOUNT_DIR/init.sh &
       $FP_MOUNT_DIR/launcher start
       rm $DP_READY
       get_reload_opt
       RELOAD_OPT=$?
       [ $RELOAD_OPT -eq $RELOAD_NONE ] && { \
       /bin/bash --login; \
       break; \
       }
       [ $RELOAD_OPT -eq $RELOAD_SYSTEM ] && { \
       reboot; \
       while [ 1 ]; do sleep 1; done; \
       }
   done

